# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSiyOdVywInc0hNcf4Xf_ueG0MtM11DU

Mounting Google Drive
"""

# To mount drive
from google.colab import drive
import os, shutil
drive.mount('/content/drive', force_remount=True)

"""Clearing the folders:
1. Folder containing the clonned git repo locally
2. Folder containing the parsed git repo files
"""

# List of folder IDs you want to clear
folder_ids_to_clear = [
    '/content/drive/MyDrive/Personal_Project/target_repo',
    '/content/drive/MyDrive/Personal_Project/repo_files_parsed_output'
]

# Clear all contents inside the folder
for folder_path in folder_ids_to_clear:
    print(f"\n--- Starting to clear folder: {folder_path} ---")
    if os.path.exists(folder_path):
        try:
            # shutil.rmtree deletes the folder and everything inside it permanently
            shutil.rmtree(folder_path)
            print(f"Successfully deleted the folder: {folder_path}")
        except Exception as e:
            print(f"Error occurred while deleting: {e}")
    else:
        print("The specified folder does not exist.")

"""Folder where all req files are stored"""

import sys

stages_0_4_files = "/content/drive/MyDrive/Personal_Project/files_req_for_main/"

if stages_0_4_files not in sys.path:
    sys.path.append(stages_0_4_files)

"""Installing libraries"""

#!pip install GitPython --quiet
#!pip install langchain_text_splitters --quiet
#!pip install tree-sitter tree-sitter-python tree-sitter-typescript tree-sitter-go tree-sitter-java tree-sitter-c_sharp tree-sitter-rust tree-sitter-c tree-sitter-cpp tree-sitter-ruby tree-sitter-kotlin tree-sitter-swift tree-sitter-zig tree-sitter-lua tree-sitter-elixir tree-sitter-perl tree-sitter-json tree-sitter-yaml tree-sitter-toml tree-sitter-hcl tree-sitter-sql tree-sitter-dockerfile tree-sitter-html tree-sitter-css tree-sitter-markdown tree-sitter-javascript --quiet

#!pip install neo4j python-dotenv --quiet
#!pip install langchain_neo4j --quiet
#!pip install langchain_ollama --quiet
#!pip install langchain_neo4j --quiet
#!pip install gitpython --quiet

#!pip install langchain_core --quiet
#!pip install tiktoken --quiet
#!pip install qwen-tokenizer --quiet

"""Clearing the Graph Vector dB (Neo4j)"""

from langchain_neo4j import Neo4jGraph

NEO4J_URI = "neo4j+s://84a1ba26.databases.neo4j.io"
NEO4J_USERNAME = "84a1ba26"
NEO4J_PASSWORD = "G10kGywmL5HNzOK-cv375bcIevG5***************" # Provide the neo4j password
NEO4J_DATABASE = "84a1ba26"

graph = Neo4jGraph(
            url=NEO4J_URI,
            username=NEO4J_USERNAME,
            password=NEO4J_PASSWORD,
            database=NEO4J_DATABASE
        )

query = "MATCH (n) DETACH DELETE n"
graph.query(query)

#Refresh the schema so LangChain knows the graph is empty
graph.refresh_schema()

"""Etablishing Connection with the Ollama server"""

#For gpu usage
# 1. Install system hardware discovery tools + zstd compression handler
#!sudo apt-get update && sudo apt-get install -y pciutils lshw zstd

# 2. Run the installer script (It will now successfully detect your NVIDIA T4 GPU)
#!curl -fsSL https://ollama.com/install.sh | sh

# Launch the Ollama server in the background and redirect output logs
#!nohup ollama serve > ollama.log 2>&1 &

"""Pulling Ollama Models locally"""

#!ollama pull qwen3-embedding:0.6b
#!ollama pull qwen2.5-coder:1.5b
#!ollama pull qwen2.5-coder:7b-instruct-q4_K_M
#!ollama list

"""Importing the files & functions"""

import cloning_git_repo_locally_and_repo_file_parser
from cloning_git_repo_locally_and_repo_file_parser import clone_or_load_repo, create_processed_repo_files

import code_and_git_ingestion_to_neo4j
from code_and_git_ingestion_to_neo4j import check_connection_langchain, ingest_data_to_neo4j

import stage0, stage1_2_3
from stage0 import stage0_process_query
from stage1_2_3 import hybrid_search_route, graph_dependency_route, git_route, step2_process_context, step2_process_git_context, QwenOllamaEngine, step3_generate_answer

"""1. Cloning the Git Repo locally to drive
2. Parsing the files using tree-sitter
3. Categorizing them into Tier 1, 2, 3.
"""

REPO_URL = "https://github.com/AyushGhatak/Drone-Photogrammetry-Optimization"  # The Repo that is to be analyzed

clone_or_load_repo(REPO_URL)
create_processed_repo_files()

"""Ingestion of the parsed Git Repo data to Graph vector Database (Neo4j)"""

check_connection_langchain()
ingest_data_to_neo4j()

"""1. Retrieval from vector dB through different stages.
2. LLM response generation
"""

def run_unified_pipeline(
    query,
    repository_name,
    ollama_client,
    engine,
    max_token_budget=5096
):

    # STAGE 0 — GUARDRAIL + ROUTING
    stage0_result = stage0_process_query(
        query=query,
        repository_name=repository_name,
        ollama_client=ollama_client
    )

    if stage0_result["status"] == "REJECTED":

        print("\n[GUARDRAIL] Stage 0: REJECTED")
        print("[GUARDRAIL] Query is outside the repository/codebase domain.")

        return {
            "status": "REJECTED",
            "answer": "Query is outside the repository/codebase domain.",
            "stage0": stage0_result
        }

    route = stage0_result["route"]

    print("\n[GUARDRAIL] Stage 0: ALLOWED")

    print("\n" + "=" * 70)
    print("UNIFIED PIPELINE")
    print("=" * 70)
    print(f"Query      : {query}")
    print(f"Route      : {route}")
    print(f"Similarity : {stage0_result['similarity']}")
    print("=" * 70)

    # STAGE 1 + STAGE 2
    if route == "HYBRID":

        print("\n[STAGE 1] Running HYBRID search route...")

        raw_results = hybrid_search_route.invoke(
            {"query_text": query}
        )

        print(f"[STAGE 1] Retrieved results: {len(raw_results)}")

        print("\n[STAGE 2] Processing HYBRID context...")

        step2_output = step2_process_context(
            query=query,
            raw_retrieval_results=raw_results,
            max_token_budget=max_token_budget,
            mode="heuristic"
        )

        print("[STAGE 2] HYBRID processing completed.")

    elif route == "GRAPH":

        print("\n[STAGE 1] Running GRAPH dependency route...")

        raw_results = graph_dependency_route.invoke(
            {"element_name": query}
        )

        if (
            isinstance(raw_results, dict)
            and "message" in raw_results
        ):

            print("\n[PIPELINE] GRAPH route returned an error.")
            print(f"[PIPELINE] {raw_results['message']}")

            return {
                "status": "ERROR",
                "answer": raw_results["message"],
                "stage0": stage0_result
            }

        print(f"[STAGE 1] Retrieved results: {len(raw_results)}")

        print("\n[STAGE 2] Processing GRAPH context...")

        step2_output = step2_process_context(
            query=query,
            raw_retrieval_results=raw_results,
            max_token_budget=max_token_budget,
            mode="graph"
        )

        print("[STAGE 2] GRAPH processing completed.")

    elif route == "GIT":

        print("\n[STAGE 1] Running GIT history route...")

        raw_results = git_route.invoke(
            {"user_query": query}
        )

        print("[STAGE 1] GIT retrieval completed.")

        print("\n[STAGE 2] Processing GIT context...")

        step2_output = step2_process_git_context(
            query=query,
            raw_git_result=raw_results,
            max_token_budget=max_token_budget
        )

        print("[STAGE 2] GIT processing completed.")

    else:

        print(f"\n[PIPELINE] ERROR — Unsupported route: {route}")

        return {
            "status": "ERROR",
            "answer": f"Unsupported route: {route}",
            "stage0": stage0_result
        }

    # STAGE 3
    print("\n[STAGE 3] Generating final answer...")

    step3_output = step3_generate_answer(
        query=query,
        step2_output=step2_output,
        ollama_engine=engine
    )

    print("[STAGE 3] Answer generation completed.")

    # FINAL RESULT
    print("\n" + "=" * 70)
    print("[PIPELINE] SUCCESS")
    print("=" * 70)
    print(f"Route         : {route}")
    print(f"Context type  : {step3_output.get('context_type', 'unknown')}")
    print("Pipeline completed successfully.")
    print("=" * 70)

    return {
        "status": "SUCCESS",
        "query": query,
        "stage0": stage0_result,
        "stage2": step2_output,
        "stage3": step3_output,
        "answer": step3_output.get("answer", "")
    }

import ollama
from sentence_transformers import CrossEncoder
from qwen_tokenizer import get_tokenizer

ollama_client = ollama.Client(
    host="http://localhost:11434"
)

ollama_engine =  QwenOllamaEngine(
    model_name="qwen2.5-coder:7b-instruct-q4_K_M",
    context_window=5096,
    temperature=0.01,
    top_p=0.95,
    max_output_tokens=1000,
)


query = "" # provide the query here
repository_name = "https://github.com/AyushGhatak/Drone-Photogrammetry-Optimization" # provide the name of the repository

result = run_unified_pipeline(
    query=query,
    repository_name=repository_name,
    ollama_client=ollama_client,
    engine=ollama_engine,
    max_token_budget=5096
)

print("\n" + "=" * 100)
print("FINAL ANSWER")
print("=" * 100)

print(result["answer"])

