# -*- coding: utf-8 -*-
"""Stage0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWwAw8tNPEH25Egapk6kCNfexVxicuHP
"""

#!pip install langchain_ollama --quiet

#For gpu usage
# 1. Install system hardware discovery tools + zstd compression handler
#!sudo apt-get update && sudo apt-get install -y pciutils lshw zstd

# 2. Run the installer script (It will now successfully detect your NVIDIA T4 GPU)
#!curl -fsSL https://ollama.com/install.sh | sh

# Launch the Ollama server in the background and redirect output logs
#!nohup ollama serve > ollama.log 2>&1 &

#!ollama pull qwen2.5-coder:7b-instruct-q4_K_M
#!ollama pull qwen3-embedding:0.6b

import ollama

ollama_client = ollama.Client(
    host="http://localhost:11434"
)

DOMAIN_GUARDRAIL_PROMPT = """
You are a repository-domain filter.

Repository:
{repository_name}

User query:
{query}

Your task is to determine whether the query could reasonably be answered
using information from the specified software repository.

Classify as:

REPOSITORY
- The query directly asks about the repository's source code, files,
  classes, methods, functions, modules, implementation, behavior,
  structure, dependencies, or architecture.
- The query asks about commits, changes, history, blame, authorship,
  revisions, or diffs.
- The query asks "why", "how", "what", "where", or "who" about something
  that may refer to the repository.
- The query is about modifying, debugging, understanding, or analyzing
  code and repository context could be relevant.
- The query does not explicitly mention the repository but could still
  reasonably refer to it.
- If the query is ambiguous but could reasonably refer to the repository,
  classify it as REPOSITORY.

GENERAL
- The query is clearly unrelated to the repository and clearly asks for
  general-world information such as weather, geography, entertainment,
  sports, general trivia, or casual conversation.
- The query clearly does not require or benefit from repository information.

Important:
When uncertain, choose REPOSITORY.

Do NOT try to determine which repository route should handle the query.
Only determine whether the repository could be relevant.

Return ONLY one of:

DOMAIN: REPOSITORY

or

DOMAIN: GENERAL
"""
def repository_domain_guardrail(
    query: str,
    repository_name: str,
    ollama_client
):
    prompt = DOMAIN_GUARDRAIL_PROMPT.format(
        repository_name=repository_name,
        query=query
    )

    response = ollama_client.generate(
        model="qwen2.5-coder:7b-instruct-q4_K_M",
        prompt=prompt,
        options={
            "temperature": 0.0,
            "num_predict": 8,
        }
    )

    result = response.get("response", "").strip().upper()

    if "DOMAIN: GENERAL" in result:
        return {
            "decision": "REJECT",
            "domain": "GENERAL"
        }

    if "DOMAIN: REPOSITORY" in result:
        return {
            "decision": "ALLOW",
            "domain": "REPOSITORY"
        }

    # Ambiguous/unexpected output:
    # allow it to proceed to the actual intent router.
    return {
        "decision": "ALLOW",
        "domain": "REPOSITORY"
    }
    
ROUTER_EXAMPLES = {

    "HYBRID": [
        "How does this functionality work?",
        "Explain how this component works.",
        "How is this feature implemented?",
        "What happens when this operation is executed?",
        "Explain the logic behind this code.",
        "How does this component process the input?",
        "What is the implementation of this functionality?",
        "How does this system handle this operation?",
        "Explain the workflow of this functionality.",
        "How does this code accomplish its task?",
        "Why does this code behave this way?",
        "What does this function do?",
    ],

    "GRAPH": [
        "What class contains this method?",
        "Which class contains this function?",
        "Where is this function defined?",
        "Where is this method declared?",
        "Where is this class located?",
        "Which class owns this method?",
        "What is the parent class of this class?",
        "Which class does this class inherit from?",
        "What class inherits from this class?",
        "Where is this code structurally located?",
        "What component contains this function?",
        "What methods are defined in this class?",
        "Which functions belong to this class?",
        "What are the child classes of this class?",
    ],

    "GIT": [
        "Who introduced this code?",
        "Who modified this functionality?",
        "Who authored this change?",
        "When was this functionality introduced?",
        "When was this change made?",
        "Who last modified this code?",
        "What commits changed this functionality?",
        "Who added this functionality?",
        "Show the history of this code.",
        "Show the revision history of this code.",
        "Who changed this code?",
        "When was this code added?",
        "Show the revision history of this code.",
        "What changes were made to this functionality?",
        "Who is the author of this file?",
        "Show the diff for this file.",
        "Show the changes made in this commit.",
        "Show me the log of changes made in this commit.",
        "Show me the full patch for this commit.",
        "Who modified this lines and what changes where made?",
        "Who originally authored the code that was moved into this file?",
    ],
}

import numpy as np
from langchain_ollama import OllamaEmbeddings

router_embeddings = OllamaEmbeddings(
    model="qwen3-embedding:0.6b",
    num_gpu=1
)

ROUTER_EXAMPLE_EMBEDDINGS = {}

for intent, examples in ROUTER_EXAMPLES.items():

    ROUTER_EXAMPLE_EMBEDDINGS[intent] = (
        router_embeddings.embed_documents(examples)
    )

def cosine_similarity(a, b):

    a = np.asarray(a)
    b = np.asarray(b)

    denominator = (
        np.linalg.norm(a) *
        np.linalg.norm(b)
    )

    if denominator == 0:
        return 0.0

    return float(np.dot(a, b) / denominator)

def classify_query_intent(query):
    query_embedding = router_embeddings.embed_query(query)

    intent_scores = {}

    for intent, example_embeddings in ROUTER_EXAMPLE_EMBEDDINGS.items():
        similarities = [
            cosine_similarity(query_embedding, example_embedding)
            for example_embedding in example_embeddings
        ]
        intent_scores[intent] = max(similarities)

    best_intent = max(
        intent_scores,
        key=intent_scores.get
    )

    best_similarity = intent_scores[best_intent]

    print("\n[INTENT ROUTER]")
    print(f"HYBRID : {intent_scores['HYBRID']:.4f}")
    print(f"GRAPH  : {intent_scores['GRAPH']:.4f}")
    print(f"GIT    : {intent_scores['GIT']:.4f}")
    print(f"Best   : {best_intent}")

    return {
        "route": best_intent,
        "similarity": best_similarity,
        "scores": intent_scores
    }

def stage0_process_query(query, repository_name, ollama_client):

    guardrail_result = repository_domain_guardrail(
        query=query,
        repository_name=repository_name,
        ollama_client=ollama_client
    )

    if guardrail_result["decision"] == "REJECT":
        return {
            "status": "REJECTED",
            "domain": "GENERAL",
            "route": None,
            "confidence": 0.0,
            "routing_mode": None
        }

    routing_result = classify_query_intent(query)

    route = routing_result["route"]
    similarity = routing_result["similarity"]

    return {
    "status": "ALLOWED",
    "domain": "REPOSITORY",
    "route": route,
    "similarity": similarity,
    "intent_scores": routing_result.get("scores", {})
}

#stage0_process_query() is called from main.py script.