# -*- coding: utf-8 -*-
"""Code_and_Git_Ingestion_to_Neo4j.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvFLh_FHUgj0CnAbODlWWuHe6BQxszaf
"""

#!pip install neo4j python-dotenv --quiet

"""Loading the embedding model"""

# 1. Install system hardware discovery tools + zstd compression handler
#!sudo apt-get update && sudo apt-get install -y pciutils lshw zstd

# 2. Run the installer script (It will now successfully detect your NVIDIA T4 GPU)
#!curl -fsSL https://ollama.com/install.sh | sh

# 3. Launch the Ollama server in the background and redirect output logs
#!nohup ollama serve > ollama.log 2>&1 &

#!ollama pull qwen3-embedding:0.6b

#!ollama list

"""Connecting with the Neo4j database"""

#!pip install langchain_neo4j --quiet

from langchain_neo4j import Neo4jGraph


def check_connection_langchain():
    # Credentials directly mapped for your scratchpad template
    NEO4J_URI = "neo4j+s://84a1ba26.databases.neo4j.io"
    NEO4J_USERNAME = "84a1ba26"
    NEO4J_PASSWORD = "G10kGywmL5HNzOK-cv375bcIevG5***************" # neo4j password to be used here.
    NEO4J_DATABASE = "84a1ba26"
    try:
        # LangChain handles driver verification automatically upon initialization
        graph = Neo4jGraph(
            url=NEO4J_URI,
            username=NEO4J_USERNAME,
            password=NEO4J_PASSWORD,
            database=NEO4J_DATABASE
        )

        # Testing a basic query execution via LangChain to guarantee schema visibility
        graph.query("RETURN 'Connection Successful!' AS test")
        print("Successfully connected to Neo4j Aura Cloud via LangChain!")

    except Exception as e:
        print("Connection failed. Check your URI, credentials, or network configuration.")
        print(f"Error Details: {e}")

#check_connection_langchain() to be called from main.py script.

#!pip install langchain_ollama --quiet
#!pip install langchain_neo4j --quiet
#!pip install gitpython --quiet

"""Git Log and Blame Analyzer"""

# LangChain Imports
from langchain_ollama import OllamaEmbeddings
from langchain_neo4j import Neo4jVector
from langchain_neo4j import Neo4jGraph

import os
import json
import datetime
from typing import List, Dict, Any
from dotenv import load_dotenv
from git import Repo

# Load credentials from .env
load_dotenv()

# Git Codebase Analyzer
class GitCodebaseAnalyzer:
    def __init__(self, repo: Repo):
        self.repo = repo
        self.working_dir = repo.working_dir

    def get_commit_logs(self, limit: int = 500) -> List[Dict[str, Any]]:
        """Extracts commit logs in a clean list-of-dicts format."""
        commit_list = []
        for commit in self.repo.iter_commits(max_count=limit):
            commit_list.append({
                "id": f"{commit.hexsha}#COMMIT",
                "entity_type": "COMMIT",
                "commit_hash": commit.hexsha,
                "author": {
                    "name": commit.author.name,
                    "email": commit.author.email
                },
                "committer": {
                    "name": commit.committer.name,
                    "email": commit.committer.email
                },
                "authored_date": datetime.datetime.fromtimestamp(commit.authored_date).isoformat(),
                "committed_date": datetime.datetime.fromtimestamp(commit.committed_date).isoformat(),
                "message": commit.message.strip(),
                "parent_hashes": [parent.hexsha for parent in commit.parents],
                "stats": {
                    "insertions": commit.stats.total.get("insertions", 0),
                    "deletions": commit.stats.total.get("deletions", 0),
                    "lines_changed": commit.stats.total.get("lines", 0),
                    "files_changed": len(commit.stats.files)
                }
            })
        return commit_list

    def get_file_blame(self, absolute_filepath: str) -> List[Dict[str, Any]]:
        """Runs a Git blame on a file and maps the author metadata of every line."""
        if not os.path.exists(absolute_filepath):
            print(f"File not found for blame: {absolute_filepath}")
            return []
        try:
            blame_raw = self.repo.git.blame("-p", absolute_filepath)
        except Exception as e:
            print(f"Error running git blame on {absolute_filepath}: {e}")
            return []
        return self._parse_porcelain_blame(blame_raw, absolute_filepath)

    def _parse_porcelain_blame(self, blame_text: str, filepath: str) -> List[Dict[str, Any]]:
        lines = blame_text.splitlines()
        commit_metadata = {}
        blame_records = []
        i, total_lines = 0, len(lines)

        while i < total_lines:
            line = lines[i]
            if not line:
                i += 1
                continue

            parts = line.split()
            sha = parts[0]
            result_line_num = int(parts[2])

            if sha not in commit_metadata:
                commit_metadata[sha] = {}
                while i < total_lines and not lines[i].startswith('\t'):
                    meta_line = lines[i]
                    if meta_line.startswith("author "):
                        commit_metadata[sha]["author_name"] = meta_line[7:]
                    elif meta_line.startswith("author-mail "):
                        commit_metadata[sha]["author_email"] = meta_line[12:].strip('<>')
                    elif meta_line.startswith("author-time "):
                        timestamp = int(meta_line[12:])
                        commit_metadata[sha]["authored_date"] = datetime.datetime.fromtimestamp(timestamp).isoformat()
                    i += 1
            else:
                while i < total_lines and not lines[i].startswith('\t'):
                    i += 1

            line_content = lines[i][1:] if i < total_lines and lines[i].startswith('\t') else ""
            blame_records.append({
                "id": f"{filepath}#LINE_{result_line_num}",
                "entity_type": "FILE_LINE_BLAME",
                "file_path": filepath,
                "line_number": result_line_num,
                "associated_commit_hash": sha,
                "author_name": commit_metadata[sha].get("author_name", "Unknown"),
                "author_email": commit_metadata[sha].get("author_email", "Unknown"),
                "authored_date": commit_metadata[sha].get("authored_date", "Unknown"),
                "line_content": line_content
            })
            i += 1
        return blame_records

"""Data Ingestion to Neo4j using Cypher Queries"""

import os
import json
from git import Repo

def ingest_complete_codebase_and_git(
    graph, ast_nodes: list, commit_logs: list, blame_records: list, batch_size: int = 1000
):
    """Executes safe batch UNWIND queries to populate structural and Git data in Neo4j."""

    # Ingest AST Structure Nodes
    ast_query = """
    UNWIND $nodes AS node

    // 1. Merge and populate AST / Sub-Chunk Node
    MERGE (n:ASTNode {id: node.id})
    SET n.name = node.name,
        n.entity_type = node.entity_type,
        n.signature = node.signature,
        n.implementation_body = node.implementation_body,
        n.associated_docstring = node.associated_docstring,
        n.parent_id = node.parent_id,
        n.parent_type = node.parent_type,

        // Scope Range Properties
        n.start_line = toInteger(node.scope_range.start_line),
        n.end_line = toInteger(node.scope_range.end_line),
        n.start_column = toInteger(node.scope_range.start_column),
        n.end_column = toInteger(node.scope_range.end_column),

        // Chunk Metadata Properties
        n.chunk_index = toInteger(node.chunk_metadata.chunk_index),
        n.total_chunks = toInteger(node.chunk_metadata.total_chunks),
        n.is_subchunked = toBoolean(node.chunk_metadata.is_subchunked),

        // Clean file path parsing across all document & code suffixes
        n.file_path = split(node.id, '#')[0]
    """

    if ast_nodes:
        print(f"Ingesting {len(ast_nodes)} AST nodes in batches of {batch_size}...")
        for i in range(0, len(ast_nodes), batch_size):
            chunk = ast_nodes[i : i + batch_size]
            graph.query(ast_query, {"nodes": chunk})

        print("Ingested AST nodes successfully!")
        # Create AST Structural Relationships
        ast_relationship_query = """
        MATCH (n:ASTNode)
        WHERE n.parent_id IS NOT NULL
          AND n.parent_id <> ""

        OPTIONAL MATCH (p:ASTNode)
        WHERE p.id = n.parent_id
          OR p.id = n.parent_id + "__CODE"
          OR p.id = n.parent_id + "#DOCUMENT"

        WITH n, p
        WHERE p IS NOT NULL

        FOREACH (_ IN CASE
            WHEN n.is_subchunked = true
            AND n.entity_type ENDS WITH "_CHUNK"
            THEN [1]
            ELSE []
        END |
            MERGE (p)-[r:HAS_CHUNK]->(n)
            SET r.parent_type = n.parent_type,
                r.chunk_index = n.chunk_index,
                r.total_chunks = n.total_chunks
        )

        FOREACH (_ IN CASE
            WHEN NOT (
                n.is_subchunked = true
                AND n.entity_type ENDS WITH "_CHUNK"
            )
            THEN [1]
            ELSE []
        END |
            MERGE (p)-[r:HAS_CHILD]->(n)
            SET r.parent_type = n.parent_type
        )
        """

        print("Creating AST parent/chunk structural relationships...")
        graph.query(ast_relationship_query)

        # Ingest Git Log History Nodes
        git_log_query = """
        UNWIND $commits AS c
        WITH c WHERE c.author IS NOT NULL AND c.commit_hash IS NOT NULL

        MERGE (a:Author {email: c.author.email})
        ON CREATE SET a.name = c.author.name

        MERGE (cm:Commit {hash: c.commit_hash})
        SET cm.message = c.message,
            cm.date = c.committed_date,
            cm.lines_changed = c.stats.lines_changed

        MERGE (a)-[:COMMITTED]->(cm)
        """

        if commit_logs:
            print(f"Ingesting {len(commit_logs)} commits in batches of {batch_size}...")
            for i in range(0, len(commit_logs), batch_size):
                chunk = commit_logs[i : i + batch_size]
                graph.query(git_log_query, {"commits": chunk})

    # Intersect Line Ranges via Blame Records
    blame_query = """
    UNWIND $blame AS b

    // Target line number
    WITH b, toInteger(b.line_number) AS blame_line
    WHERE blame_line IS NOT NULL

    MATCH (n:ASTNode)
    WHERE n.file_path = b.file_path
      AND n.start_line IS NOT NULL
      AND n.end_line IS NOT NULL
      AND toInteger(n.start_line) <= blame_line
      AND toInteger(n.end_line) >= blame_line

    // Pick the innermost/most specific AST node (smallest line span)
    WITH b, n, (toInteger(n.end_line) - toInteger(n.start_line)) AS line_span
    ORDER BY line_span ASC
    WITH b, collect(n)[0] AS target_node
    WHERE target_node IS NOT NULL

    // Link Author and Commit
    MERGE (a:Author {email: b.author_email})
    MERGE (cm:Commit {hash: b.associated_commit_hash})

    MERGE (a)-[:DEVELOPED]->(target_node)
    MERGE (cm)-[:MODIFIED_STRUCTURE]->(target_node)
    """

    if blame_records:
        print(f"Ingesting {len(blame_records)} blame records in batches of {batch_size}...")
        for i in range(0, len(blame_records), batch_size):
            chunk = blame_records[i : i + batch_size]
            graph.query(blame_query, {"blame": chunk})

    # Chain Sequential Text Chunks via NEXT_DOCUMENT_CHUNK
    next_doc_chunk_query = """
    MATCH (c:ASTNode)
    WHERE c.entity_type = 'TEXT_DOCUMENT_CHUNK'

    WITH coalesce(c.parent_id, split(c.id, '#')[0]) AS parent_group, c,
         CASE
           WHEN c.chunk_index IS NOT NULL THEN toInteger(c.chunk_index)
           WHEN c.id CONTAINS '#DOCUMENT_PART_' THEN toInteger(split(c.id, '#DOCUMENT_PART_')[1])
           ELSE toInteger(c.start_line)
         END AS calculated_index

    WITH parent_group, c ORDER BY calculated_index ASC, c.id ASC
    WITH parent_group, collect(c) AS chunks
    WHERE size(chunks) > 1

    UNWIND range(0, size(chunks) - 2) AS i
    WITH chunks[i] AS current_chunk, chunks[i + 1] AS next_chunk
    MERGE (current_chunk)-[:NEXT_DOCUMENT_CHUNK]->(next_chunk)
    """

    print("Linking sequential text chunks via NEXT_DOCUMENT_CHUNK...")
    graph.query(next_doc_chunk_query)

    # Chain Sequential Code Chunks via NEXT_CODE_CHUNK
    next_code_chunk_query = """
    MATCH (c:ASTNode)
    WHERE c.entity_type ENDS WITH '_CHUNK'
      AND c.entity_type <> 'TEXT_DOCUMENT_CHUNK'

    WITH coalesce(c.parent_id, split(c.id, '#')[0]) AS parent_group, c,
         CASE
           WHEN c.chunk_index IS NOT NULL THEN toInteger(c.chunk_index)
           WHEN c.id CONTAINS '__CODE_PART_' THEN toInteger(split(c.id, '__CODE_PART_')[1])
           ELSE toInteger(c.start_line)
         END AS calculated_index

    WITH parent_group, c ORDER BY calculated_index ASC, c.id ASC
    WITH parent_group, collect(c) AS chunks
    WHERE size(chunks) > 1

    UNWIND range(0, size(chunks) - 2) AS i
    WITH chunks[i] AS current_chunk, chunks[i + 1] AS next_chunk
    MERGE (current_chunk)-[:NEXT_CODE_CHUNK]->(next_chunk)
    """

    print("Linking sequential code chunks via NEXT_CODE_CHUNK...")
    graph.query(next_code_chunk_query)

import os
import json

# PHASE 1 & PHASE 2 DATA COLLECTION PIPELINE

def phase_1_ingest_ast(gdrive_folder_path):
    print("Starting Phase 1: Ingesting AST Structural Files...")
    all_ast_nodes = []

    if not os.path.exists(gdrive_folder_path):
        print(f"Error: Path '{gdrive_folder_path}' does not exist.")
        return all_ast_nodes

    for filename in os.listdir(gdrive_folder_path):
        if filename.endswith(".json"):
            file_json_path = os.path.join(gdrive_folder_path, filename)
            with open(file_json_path, "r", encoding="utf-8") as f:
                try:
                    data = json.load(f)
                    nodes_list = data if isinstance(data, list) else data.get("nodes", [])
                    all_ast_nodes.extend(nodes_list)
                except Exception as e:
                    print(f"Error reading JSON file {filename}: {e}")

    print(f"Loaded {len(all_ast_nodes)} AST elements from Drive.")
    return all_ast_nodes


# Extensions to skip during Git blame harvesting
BINARY_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".svg",
    ".pdf", ".zip", ".tar", ".gz", ".7z",
    ".pyc", ".pyo", ".so", ".dll", ".exe", ".bin",
    ".woff", ".woff2", ".ttf", ".eot"
}

def phase_2_harvest_git_blame(all_ast_nodes, local_repo_path, analyzer):
    print("\nStarting Phase 2: Harvesting Git Blame History...")
    all_blame_records = []
    unique_files = set()

    for node in all_ast_nodes:
        node_id = node.get("id", "")
        if "#" in node_id:
            file_path = node_id.split("#")[0]
            if file_path:
                unique_files.add(file_path)

    print(f"Discovered {len(unique_files)} unique target files to analyze.")

    for relative_path in unique_files:
        clean_rel = relative_path.lstrip("/")

        # Skip .git internal files and binary assets
        if clean_rel.startswith(".git/") or any(clean_rel.lower().endswith(ext) for ext in BINARY_EXTENSIONS):
            continue

        absolute_target_file = os.path.normpath(os.path.join(local_repo_path, clean_rel))

        try:
            file_blames = analyzer.get_file_blame(absolute_target_file)
            if file_blames:
                for record in file_blames:
                    record["file_path"] = relative_path
                all_blame_records.extend(file_blames)
        except Exception as e:
            print(f"  [Warning] Could not harvest blame for '{clean_rel}': {e}")

    print(f"Harvested {len(all_blame_records)} blame interaction records.")
    return all_blame_records

import os
from git import Repo
from langchain_ollama import OllamaEmbeddings
from langchain_neo4j import Neo4jVector
from langchain_neo4j import Neo4jGraph

# MAIN ORCHESTRATOR

def run_orchestrator(gdrive_folder_path: str, local_repo_path: str):
    """Reads JSON files, cross-references local Git history, and ingests safely into Neo4j."""
    print("Inspecting Git Target Project Metadata...")
    repo = Repo(local_repo_path)

    print(f"Evaluating JSON files inside directory: {gdrive_folder_path}...")
    if not os.path.exists(gdrive_folder_path):
        raise FileNotFoundError(f"Drive path target not discovered: {gdrive_folder_path}")

    # Initialize Git analyzer
    analyzer = GitCodebaseAnalyzer(repo)

    # 1. Gather all file components
    all_ast_nodes = phase_1_ingest_ast(gdrive_folder_path)

    # 2. Gather global commits
    print("\nCollecting global commit histories...")
    all_commits = analyzer.get_commit_logs(limit=300)

    # 3. Harvest ownership data via blame
    all_blame_records = phase_2_harvest_git_blame(all_ast_nodes, local_repo_path, analyzer)

    unique_authors = set()
    for commit in all_commits:
        if commit.get("author_email"):
            unique_authors.add(commit["author_email"])

    for record in all_blame_records:
        if record.get("author_email"):
            unique_authors.add(record["author_email"])

    print(f"Total unique contributors found across all history: {len(unique_authors)}")

    total_predicted_nodes = len(all_ast_nodes) + len(all_commits) + len(unique_authors)
    max_allowed_nodes = 195000  # Aura Free Ceiling Limit

    print(f"\nPre-flight Analysis:")
    print(f" -> AST Structural Elements: {len(all_ast_nodes)}")
    print(f" -> Commits Tracked:         {len(all_commits)}")
    print(f" -> Unique Contributors:    {len(unique_authors)}")
    print(f" -> Total Blame Records:    {len(all_blame_records)}")
    print(f" -> Total Expected Nodes:    {total_predicted_nodes:,} / {max_allowed_nodes:,}")

    if total_predicted_nodes >= max_allowed_nodes:
        print("\nIngestion Aborted: Expected nodes exceed Neo4j Aura free limits.")
        return None

    print("\nCapacity check passed. Initiating Database Ingestion Pipeline...")

    # Fetch configuration from Environment Variables or Fallback
    NEO4J_URI = os.getenv("NEO4J_URI", "neo4j+s://84a1ba26.databases.neo4j.io")
    NEO4J_USERNAME = os.getenv("NEO4J_USERNAME", "84a1ba26")
    NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "G10kGywmL5HNzOK-cv375bcIevG5***************")
    NEO4J_DATABASE = os.getenv("NEO4J_DATABASE", "84a1ba26")

    graph = Neo4jGraph(
        url=NEO4J_URI,
        username=NEO4J_USERNAME,
        password=NEO4J_PASSWORD,
        database=NEO4J_DATABASE,
    )

    # Corrected Schema Constraints and Indexes (Standard Cypher Syntax)
    graph.query("CREATE CONSTRAINT IF NOT EXISTS FOR (n:ASTNode) REQUIRE n.id IS UNIQUE;")
    graph.query("CREATE CONSTRAINT IF NOT EXISTS FOR (a:Author) REQUIRE a.email IS UNIQUE;")
    graph.query("CREATE CONSTRAINT IF NOT EXISTS FOR (c:Commit) REQUIRE c.hash IS UNIQUE;")
    graph.query("CREATE INDEX IF NOT EXISTS FOR (n:ASTNode) ON (n.file_path);")

    print("Index constraints verified and active!")

    # Ingest Graph Structure in Batches
    print("\nPushing Code architecture structure and Git parameters into Neo4j...")
    ingest_complete_codebase_and_git(
        graph, all_ast_nodes, all_commits, all_blame_records, batch_size=1000
    )

    # Clean execution for vector indexing (Drops outdated vector index if model dimensions changed)
    try:
        graph.query("DROP INDEX code_ast_index IF EXISTS")
    except Exception:
        pass

    print("Fetching enriched AST metadata for embeddings...")

    embedding_nodes = graph.query("""
    MATCH (n:ASTNode)
    WHERE n.name IS NOT NULL AND n.entity_type IS NOT NULL

    OPTIONAL MATCH (p:ASTNode)-[:HAS_CHILD]->(n)
    OPTIONAL MATCH (n)-[:HAS_CHILD]->(c)
    OPTIONAL MATCH (n)-[:HAS_CHUNK]->(chunk)

    WITH
        n,
        p,
        collect(DISTINCT c.name) AS children,
        collect(DISTINCT chunk.name) AS chunks,
        coalesce(n.file_path, split(n.id, '#')[0]) AS clean_file_path

    RETURN
        n.id AS id,
        n.name AS name,
        n.entity_type AS entity_type,
        n.signature AS signature,
        clean_file_path AS file_path,
        n.associated_docstring AS associated_docstring,
        n.implementation_body AS implementation_body,
        n.start_line AS start_line,
        n.end_line AS end_line,
        p.name AS parent_name,
        p.entity_type AS parent_entity_type,
        children,
        chunks
    """)

    # Initialize Ollama Server and Embeddings Model
    EMBED_MODEL_NAME = "qwen3-embedding:0.6b"
    print(f"\nStarting Ollama service and fetching '{EMBED_MODEL_NAME}'...")
    os.system("nohup ollama serve > ollama.log 2>&1 &")
    os.system(f"sleep 5 && ollama pull {EMBED_MODEL_NAME}")

    embeddings = OllamaEmbeddings(model=EMBED_MODEL_NAME)

    # Compute Local Embeddings for AST Nodes
    print("Computing specialized local embeddings for Code and Document AST nodes...")
    nodes_to_embed = []

    # Document entity types to check against
    DOC_TYPES = {"TEXT_DOCUMENT", "TEXT_DOCUMENT_CHUNK", "DOCUMENT", "DOCUMENT_CHUNK"}

    for node in embedding_nodes:
        entity_type = (node.get("entity_type") or "").upper()
        file_path = node.get("file_path") or ""
        chunk_names = ", ".join(
            x for x in node.get("chunks", []) if x
        )

        # Branch 1: Document / Text Payloads
        if entity_type in DOC_TYPES or "#DOCUMENT" in node.get("id", ""):
            section = node.get("parent_name") or "Main Document"
            text_payload = f"""
            Document Path:
            {file_path}\n
            Section / Parent Heading:
            {section}\n
            Entity Type:
            {entity_type}\n
            Document Content:
            {node.get("implementation_body", "") or node.get("associated_docstring", "")}\n
            Associated Document Chunks:
            {chunk_names if chunk_names else "None"}\n
            """.strip()

        # Branch 2: Code AST Payloads
        else:
            module = (
                file_path
                .replace("src/", "")
                .replace("/", ".")
            )
            children = ", ".join(
                x for x in node.get("children", []) if x
            )

            text_payload = f"""
            Symbol Name:
            {node.get("name", "")}\n
            Symbol Type:
            {entity_type}\n
            Module:
            {module}\n
            Member Of:
            {node.get("parent_name") or "Top-Level"}\n
            Parent Type:
            {node.get("parent_entity_type") or "None"}\n
            Child Symbols:
            {children if children else "None"}\n
            Declaration:
            {node.get("signature", "")}\n
            Documentation:
            {node.get("associated_docstring", "")}\n
            Source Lines:
            {node.get("start_line", "?")} - {node.get("end_line", "?")}\n
            Source Code:
            {node.get("implementation_body", "")}\n
            Associated Code Chunks:
            {chunk_names if chunk_names else "None"}\n
            """.strip()

        nodes_to_embed.append({"id": node["id"], "text": text_payload})

    texts_list = [n["text"] for n in nodes_to_embed]

    # Batch embedding calculations to avoid RAM spikes
    print("Generating vector embeddings in chunks...")
    computed_vectors = []
    embed_batch_size = 250
    for i in range(0, len(texts_list), embed_batch_size):
        chunk_texts = texts_list[i : i + embed_batch_size]
        chunk_vectors = embeddings.embed_documents(chunk_texts)
        computed_vectors.extend(chunk_vectors)

    # Build DB update payload
    batch_payload = [
        {
            "id": nodes_to_embed[idx]["id"],
            "embedding": computed_vectors[idx],
            "embedding_text": nodes_to_embed[idx]["text"]
        }
        for idx in range(len(nodes_to_embed))
    ]

    # Push Embeddings in Batches to Neo4j
    print(f"Pushing batched vectors directly to database '{NEO4J_DATABASE}'...")
    vector_push_query = """
    UNWIND $batch AS item
    MATCH (n:ASTNode {id: item.id})
    SET
        n.embedding = item.embedding,
        n.embedding_text = item.embedding_text
    """
    push_batch_size = 1000
    for i in range(0, len(batch_payload), push_batch_size):
        chunk = batch_payload[i : i + push_batch_size]
        graph.query(vector_push_query, {"batch": chunk})

    # Finalize Vector Store Binding
    print("Finalizing LangChain vector store index connections...")
    code_vector_store = Neo4jVector.from_existing_graph(
        embedding=embeddings,
        url=NEO4J_URI,
        username=NEO4J_USERNAME,
        password=NEO4J_PASSWORD,
        database=NEO4J_DATABASE,
        index_name="code_ast_index",
        node_label="ASTNode",
        text_node_properties=["embedding_text"],
        embedding_node_property="embedding",
    )

    print("\nPipeline Execution Completed Successfully!")
    return code_vector_store

import os
from google.colab import drive

def ingest_data_to_neo4j():

    # Mount Drive securely
    if not os.path.exists('/content/drive'):
        drive.mount('/content/drive')
        print("Drive mounted successfully.")
    else:
        print("Drive is already mounted.")

    # Path configuration where your Drive structures or Google Drive Mount strings are handled
    GDRIVE_JSON_DIR = "/content/drive/MyDrive/Personal_Project/repo_files_parsed_output"
    LOCAL_REPO_DIR = "/content/drive/MyDrive/Personal_Project/target_repo"

    # Launch Pipeline
    run_orchestrator(gdrive_folder_path=GDRIVE_JSON_DIR, local_repo_path=LOCAL_REPO_DIR)
    
#ingest_data_to_neo4j() is called from main.py script.

